### ISSUE TITLE
Arquivos maiores "congelam" sessão

### ISSUE THREAD

**Issue by diegoromal** [wppconnect-team/server-cli#176]
Ao enviar vídeos "maiores" do whatsapp para o wppconnect e vice versa, recebo o erro abaixo e o serviço "congela", necessitando "ler" a mensagem no celular com whatsapp e reiniciar o serviço em seguida. 
- Ao enviar do wppconnect para o whatsapp, apesar do erro, a mensagem é entregue, porém o serviço para.
- Entendo ser importante um limite de tamanho, mas poderia ser igual ao do próprio whatsapp, além disso, ao meu ver não deveria causar danos ao wppconnect.
- O vídeo utilizado no teste tem 8.3M com 47s de duração
- Estou usando o server-cli no docker

![image](https://user-images.githubusercontent.com/13037189/151854275-3d6bd0ae-ae13-4274-be1c-3873f96a347b.png)

**Comment by renat473** [comment]
Olá,

faça atualização de versão, problema solucionado nas versões anteriores;
