### ISSUE TITLE
Problemas ao reinstalar wppConnect

### ISSUE THREAD

**Issue by Douglas09** [wppconnect-team/server-cli#23]
Olá, eu tenho um servidor Windows server onde eu havia instalado por um usuário o WPPConnect utilizando:

### **yarn global add @wppconnect/server-cli**

e estava funcionando tudo bem... Porem, resolvi trocar o usuário para um administrador, então removi o pacote usando:

### **yarn global remove @wppconnect/server-cli**

Wppconnect foi removido com sucesso.
Apaguei o usuário anterior do windows e tentei instalar novamente o WPPConnect neste novo usuário usando:

### **yarn global add @wppconnect/server-cli**

Então o wpp é instalado com sucesso, porem não reconhece o comando de inicialização:

### **wppserver --port 8000**

Alguém poderia me auxiliar com isto?

**Comment by edgardmessias** [comment]
Desculpe a demora em responder.

Isso provavelmente deve ser um problema com as variáveis ambientes.

Veja se está no PATH os locais do yarn global.
