### ISSUE TITLE
Erro em Mac M2

### ISSUE THREAD

**Issue by Megamil** [wppconnect-team/server-cli#444]
Tentei executar no docker assim:

docker % docker run -p 8080:8080 --name wppconnect-server-cli --rm wppconnect/server-cli:1.3.7 wppserver --secretKey My53c3tKY --port 8080 --frontend
Unable to find image 'wppconnect/server-cli:1.3.7' locally
1.3.7: Pulling from wppconnect/server-cli
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

minha maquina é um MacBook Pro M2 Max, acredito que seja erro de arquitetura.

**Comment by renat473** [comment]
Olá,

A imagem criada do docker foi com base de arquitetura x32 e x64, tente criar uma imagem personalizada para sua arquitetura.
