### ISSUE TITLE
Parametros de configuração

### ISSUE THREAD

**Issue by jeffsmor** [wppconnect-team/server-cli#483]
Alguma possibilidade de adicionar o restante das configurações do wppconnect-server?

https://github.com/wppconnect-team/wppconnect-server/blob/main/src/config.ts

**Comment by renat473** [comment]
olá,

Já existe está funcionalidade , `program.option('-c, --config <path>', 'Arquivo JSON de configuração para inicialização');`

Para informações dos paramêtros disponível : https://github.com/wppconnect-team/server-cli/blob/193ec68a237e2018d36cc427a01bd9e04b2672a7/src/program.js#L28C1-L28C90
